---
driver:
  name: vagrant

provisioner:
  name: policyfile_zero
  require_chef_omnibus: 12
  data_bags_path: data_bags
  encrypted_data_bag_secret_key_path: .chef/encrypted_data_bag_secret

platforms:
  - name: ubuntu-14.04
    driver:
      box: express42/ubuntu-14.04
  - name: ubuntu-16.04
    driver:
      box: express42/ubuntu-16.04

suites:
  - name: base
    provisioner:
      policyfile: policies/base.rb

  - name: chef-server
    provisioner:
      policyfile: policies/chef-server.rb
    driver:
      customize:
        <%= ENV['VAGRANT_DEFAULT_PROVIDER'] == 'parallels' ? 'memsize' : 'memory' %>: 2048
  - name: graylog-server
    provisioner:
      policyfile: policies/graylog-server.rb
    driver:
      customize:
        <%= ENV['VAGRANT_DEFAULT_PROVIDER'] == 'parallels' ? 'memsize' : 'memory' %>: 2048
  - name: zabbix-server
    provisioner:
      policyfile: policies/zabbix-server.rb

  - name: all
    provisioner:
      policyfile: policies/all.rb
